### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6551: ordinal not in range(128)

### ISSUE THREAD

**Issue by yougotwill** [predragnikolic/SIDE#3]
Giving this plugin a go and noticed this error in the console.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 283, in on_api_ready
    m.plugin_loaded()
  File "/Users/neon/Library/Application Support/Sublime Text 3/Packages/SIDE/main.py", line 31, in plugin_loaded
    index_view(view)
  File "/Users/neon/Library/Application Support/Sublime Text 3/Packages/SIDE/features/indexer.py", line 74, in index_view
    content = file.read()
  File "./python3.3/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6551: ordinal not in range(128)
```

**Comment by predragnikolic** [comment]
Hello, 

I didn't try this, but I think this should fix it. Can you paste this `open(absolute_file_path, 'r', encoding='utf-8')` on this line and see if it fixes your problem?

https://github.com/predragnikolic/SIDE/blob/758613f1f771a2fb75dbd8ac4f69eda5191e9675/features/indexer.py#L62

**Comment by yougotwill** [comment]
@predragnikolic Can confirm that fixes it. Thank you for the quick response! 🙏

**Comment by predragnikolic** [comment]
One bug less :-)
Do you want do do a PR?

**Comment by yougotwill** [comment]
Sure thing, I actually just forked it for future work but might as well.

**Comment by predragnikolic** [comment]
Thanks, that was quick :-)
